class StringConstants {
  static const String appName = 'Take Home';
  static const String strPostList = 'Post List';
  static const String strPost = 'Post';
  static const String strShowLess = 'Show Less';
  static const String strShowMore = 'Show More';
  static const String str2HoursAgo = '2 hours ago';
  static const String strDelete = 'Delete';

  static const userNameList = <String>[
    "Dylan Springer",
    "William Avery",
    "Evan Ogden",
    "Kylie Wilkins",
    "Lillian Walsh",
    "Paul Burgess",
    "Diana MacLeod",
    "Adrian Terry",
    "Eric Welch",
    "Sue Sutherland",
    "Ava Bailey",
    "Jessica Carr",
    "Max Berry",
    "Cameron Davies",
    "Ruth Hart",
    "Melanie Lambert",
    "Una Pullman",
    "Leonard Edmunds",
    "Elizabeth Butler",
    "Caroline Nash",
    "Dorothy Butler",
    "Karen Allan",
    "Diana Forsyth",
    "Peter Piper",
    "Peter Robertson",
    "Adrian Greene",
    "Joan MacLeod",
    "Sean May",
    "Justin McDonald",
    "Matt Roberts",
    "Theresa Parsons",
    "Harry Lawrence",
    "Frank Robertson",
    "Eric Ellison",
    "Joseph Robertson",
    "Sam Graham",
    "Cameron Paige",
    "James Hill",
    "Tim Peake",
    "Julian May",
    "Frank Young",
    "Joe MacDonald",
    "Sue Vance",
    "Christopher Wright",
    "Peter Baker",
    "Irene Robertson",
    "Adam Murray",
    "Owen Graham",
    "Dorothy Rees",
    "Sean Lewis",
    "Bella Underwood",
    "Dan Ball",
    "Katherine Chapman",
    "Angela Parr",
    "Kylie King",
    "Heather Baker",
    "Theresa Young",
    "Leah Wright",
    "Justin Clarkson",
    "Stewart Parr",
    "Michelle Quinn",
    "Leonard Simpson",
    "Jasmine Hughes",
    "Irene Payne",
    "Neil Paterson",
    "Brian Parr",
    "Joseph Bell",
    "Heather Fraser",
    "Una Jackson",
    "Cameron Paterson",
    "Jessica Henderson",
    "Lucas Burgess",
    "Joan James",
    "Simon Mitchell",
    "Alan Johnston",
    "Leah Ball",
    "Victor Black",
    "Keith Sanderson",
    "Rebecca Lambert",
    "Emma Peters",
    "Sally Scott",
    "Jack Powell",
    "Dominic Anderson",
    "Karen Mackay",
    "Austin MacDonald",
    "Neil Jackson",
    "Jack Manning",
    "Pippa Thomson",
    "Jessica Cameron",
    "Colin Hunter",
    "Alan Bower",
    "Alison Smith",
    "Joseph Rees",
    "Yvonne Short",
    "Richard McGrath",
    "Madeleine Morrison",
    "Andrea Paige",
    "Benjamin Short",
    "Dominic Simpson",
    "Austin Morrison",
  ];
}

/// Routes
class Routes {
  static const String splashPage = "/splashPage";
  static const String postsPage = "/postsPage";
  static const String postDetailPage = "/postDetailPage";
}
